Issue/46 - Fix magic methods not working as intended
berlindb/core pull request #47
Opened 2020-05-06 02:57 UTC by JJJ

This pull request changes quite a bit about how classes store their properties.

* Everything gets stored in a `$this->data` array
* Magic methods in `Base` have internal logic for allowing `get_` functions to work as intended
* Any variable that tries to get set to `$this->foo` ends up in `$this->data['foo']` so that it can always be magically overridden, or not

All of this is required to make overrides work as intended. But then, WordPress functions that use `WP_List_Util` will then stop working, because they use `array_key_exists()` which will bypass PHP magic methods completely.

That means this PR either requires:
* an upstream fix to WordPress Core
* shimming that utility internally so that it does not require WordPress in this situation

Fixes #46.

Related to: https://core.trac.wordpress.org/ticket/50095

2020-08-25 20:38 UTC, JJJ commented
The above upstream WordPress core change was merged into WordPress 5.5!

This PR can get a little simpler because of that.

2020-08-25 23:29 UTC, alexstandiford commented
So should we assume that anything using BerlinDB should be on 5.5 or greater?

2020-08-26 02:32 UTC, JJJ commented
> So should we assume that anything using BerlinDB should be on 5.5 or greater?

Once this is merged, yes.

2021-09-08 17:37 UTC, alexstandiford requested changes
Just adding a note that it would be a good idea to add a note in the Readme that BerlinDB currently requires a minimum of WordPress 5.5. This may be a detriment to some plugins that want to be compatible further than that.

2021-09-08 23:19 UTC, JJJ commented
> add a note in the Readme

👍

> BerlinDB currently requires a minimum of WordPress 5.5

It doesn't _yet_, but it will when #46 is resolved, which is in the Ongoing milestone for pretty much this reason.

Based on the WordPress functions that Berlin uses, its minimum is _probably_ 3.3 thanks to it calling `wp_suspend_cache_addition()` in `Query::cache_set()`.

That's a pretty big jump from 3.3 to 5.5, so I'm not super eager to merge this. 😬

2021-09-08 23:20 UTC, alexstandiford commented
Yep, totally understandable.

2026-05-27 19:04 UTC, JJJ commented
Closing this without merging because the implementation has been superseded by the current 3.x architecture.

The magic getter behavior now lives in `Traits\Magic`, and construction/per-run state has moved into `Traits\Boot` and `Traits\Lifecycle`. This PR also targets the older file layout (`src/Database/Base.php`, `src/Database/Query.php`, `src/Database/Queries/*`), so it no longer applies cleanly to the current structure.

Issue #46 should stay open, though. The remaining problem appears to be narrower now: protected properties can still be accessed directly by sibling subclasses, bypassing `__get()`. A fresh fix should probably investigate property visibility/private storage against the current `Traits` and `Kern` classes.

Thanks, past us, for doing the hard thinking here 💞

2026-05-27 19:04 UTC, closed without merging