Issue/57 - Improve Query constructor documentation
berlindb/core pull request #68
Opened 2020-08-20 13:02 UTC by alexstandiford

This PR adds a tweak to the documentation for the query constructor. It clarifies how date queries can be used.

2020-08-20 13:32 UTC, ashleyfae requested changes

2020-08-20 13:32 UTC, ashleyfae commented on query.php
> +c<?php
```suggestion
<?php
```

Whoopsies.

2020-08-20 14:13 UTC, alexstandiford commented on query.php
> +c<?php
Whoopsies indeed. 🤦

2020-08-25 11:09 UTC, ashleyfae approved these changes

2020-09-29 02:57 UTC, merged